<?php
/**
 * Export full database schema to database/schema.sql
 *
 * Usage: php scripts/export_db_schema.php
 * It reads DB credentials from the project's .env file.
 */

function parseEnv($path)
{
    if (!file_exists($path)) {
        throw new RuntimeException(".env file not found: $path");
    }
    $lines = file($path, FILE_IGNORE_NEW_LINES | FILE_SKIP_EMPTY_LINES);
    $env = [];
    foreach ($lines as $line) {
        $line = trim($line);
        if ($line === '' || strpos($line, '#') === 0) {
            continue;
        }
        if (strpos($line, '=') === false) {
            continue;
        }
        list($k, $v) = explode('=', $line, 2);
        $env[trim($k)] = trim($v);
    }
    return $env;
}

function quoteName($name)
{
    return "`" . str_replace("`", "``", $name) . "`";
}

try {
    $env = parseEnv(__DIR__ . '/../.env');
    $host = $env['DB_HOST'] ?? '127.0.0.1';
    $db   = $env['DB_NAME'] ?? '';
    $user = $env['DB_USER'] ?? '';
    $pass = $env['DB_PASS'] ?? '';

    if (!$db) {
        throw new RuntimeException('DB_NAME not set in .env');
    }

    $dsn = "mysql:host={$host};dbname={$db};charset=utf8mb4";
    $pdo = new PDO($dsn, $user, $pass, [
        PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
        PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
    ]);

    $out = [];
    $out[] = "-- Generated by scripts/export_db_schema.php on " . date('c');
    $out[] = "-- Source .env: " . realpath(__DIR__ . '/../.env');
    $out[] = "-- DB_HOST={$host}  DB_NAME={$db}  DB_USER={$user}  DB_PASS={$pass}";
    $out[] = "SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS;";
    $out[] = "SET FOREIGN_KEY_CHECKS=0;";
    $out[] = "\n";

    // Export tables
    $tablesStmt = $pdo->query("SHOW FULL TABLES WHERE Table_type = 'BASE TABLE'");
    $tables = $tablesStmt->fetchAll(PDO::FETCH_NUM);
    foreach ($tables as $row) {
        $table = $row[0];
        $out[] = "-- --------------------------------------------------------";
        $out[] = "DROP TABLE IF EXISTS " . quoteName($table) . ";";
        $create = $pdo->query("SHOW CREATE TABLE " . quoteName($table))->fetch(PDO::FETCH_ASSOC);
        // SHOW CREATE TABLE returns array with keys 'Table' and 'Create Table' (or localized)
        $createSql = null;
        foreach ($create as $k => $v) {
            if (stripos($k, 'CREATE') !== false) {
                $createSql = $v;
                break;
            }
        }
        if ($createSql === null) {
            // fallback: take last column
            $vals = array_values($create);
            $createSql = end($vals);
        }
        $out[] = $createSql . ";\n";
    }

    // Export views
    $viewsStmt = $pdo->query("SHOW FULL TABLES WHERE Table_type = 'VIEW'");
    $views = $viewsStmt->fetchAll(PDO::FETCH_NUM);
    foreach ($views as $row) {
        $view = $row[0];
        $out[] = "-- --------------------------------------------------------";
        $out[] = "DROP VIEW IF EXISTS " . quoteName($view) . ";";
        $create = $pdo->query("SHOW CREATE VIEW " . quoteName($view))->fetch(PDO::FETCH_ASSOC);
        $createSql = null;
        foreach ($create as $k => $v) {
            if (stripos($k, 'CREATE') !== false) {
                $createSql = $v;
                break;
            }
        }
        if ($createSql === null) {
            $vals = array_values($create);
            $createSql = end($vals);
        }
        $out[] = $createSql . ";\n";
    }

    // Export triggers
    $triggersStmt = $pdo->query("SHOW TRIGGERS");
    $triggers = $triggersStmt->fetchAll(PDO::FETCH_ASSOC);
    foreach ($triggers as $t) {
        $name = $t['Trigger'] ?? $t['trigger'] ?? null;
        if (!$name) continue;
        $out[] = "-- --------------------------------------------------------";
        $out[] = "DROP TRIGGER IF EXISTS " . quoteName($name) . ";";
        try {
            $create = $pdo->query("SHOW CREATE TRIGGER " . quoteName($name))->fetch(PDO::FETCH_ASSOC);
            $createSql = null;
            foreach ($create as $v) {
                if (stripos($v, 'CREATE') !== false) { $createSql = $v; break; }
            }
            if ($createSql) $out[] = $createSql . ";\n";
        } catch (Exception $e) {
            // Some MySQL versions may not support SHOW CREATE TRIGGER; skip
            $out[] = "-- Could not retrieve CREATE TRIGGER for " . $name . " (" . $e->getMessage() . ")";
        }
    }

    // Export routines (procedures and functions)
    $routines = $pdo->query("SELECT ROUTINE_NAME, ROUTINE_TYPE FROM information_schema.ROUTINES WHERE ROUTINE_SCHEMA = " . $pdo->quote($db))->fetchAll(PDO::FETCH_ASSOC);
    foreach ($routines as $r) {
        $name = $r['ROUTINE_NAME'];
        $type = strtoupper($r['ROUTINE_TYPE']);
        $out[] = "-- --------------------------------------------------------";
        $out[] = "DROP " . $type . " IF EXISTS " . quoteName($name) . ";";
        try {
            $create = $pdo->query("SHOW CREATE " . $type . " " . quoteName($name))->fetch(PDO::FETCH_ASSOC);
            $createSql = null;
            foreach ($create as $k => $v) {
                if (stripos($k, 'CREATE') !== false) { $createSql = $v; break; }
            }
            if ($createSql === null) { $vals = array_values($create); $createSql = end($vals); }
            $out[] = $createSql . ";\n";
        } catch (Exception $e) {
            $out[] = "-- Could not retrieve CREATE " . $type . " for " . $name . " (" . $e->getMessage() . ")";
        }
    }

    $out[] = "SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;";

    $sql = implode("\n", $out) . "\n";

    $target = __DIR__ . '/../database/schema.sql';
    if (file_put_contents($target, $sql) === false) {
        throw new RuntimeException("Failed to write schema to $target");
    }

    echo "Schema exported to $target\n";
} catch (Exception $e) {
    fwrite(STDERR, "Error: " . $e->getMessage() . "\n");
    exit(1);
}

